config/routes.rb
Battleofthebands::Application.routes.draw do
  resources :songs

  resources :bands

end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :songs
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :band
  has_attached_file :audio

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  # GET /bands
  # GET /bands.xml
  def index
    @bands = Band.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bands }
    end
  end

  # GET /bands/1
  # GET /bands/1.xml
  def show
    @band = Band.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @band }
    end
  end

  # GET /bands/new
  # GET /bands/new.xml
  def new
    @band = Band.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @band }
    end
  end

  # GET /bands/1/edit
  def edit
    @band = Band.find(params[:id])
  end

  # POST /bands
  # POST /bands.xml
  def create
    @band = Band.new(params[:band])

    respond_to do |format|
      if @band.save
        format.html { redirect_to(@band, :notice => 'Band was successfully created.') }
        format.xml  { render :xml => @band, :status => :created, :location => @band }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @band.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bands/1
  # PUT /bands/1.xml
  def update
    @band = Band.find(params[:id])

    respond_to do |format|
      if @band.update_attributes(params[:band])
        format.html { redirect_to(@band, :notice => 'Band was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @band.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.xml
  def destroy
    @band = Band.find(params[:id])
    @band.destroy

    respond_to do |format|
      format.html { redirect_to(bands_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.xml
  def index
    @songs = Song.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.xml
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.xml
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.xml
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to(@song, :notice => 'Song was successfully created.') }
        format.xml  { render :xml => @song, :status => :created, :location => @song }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @song.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.xml
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to(@song, :notice => 'Song was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @song.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.xml
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to(songs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_area :website %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br />
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :myspace %><br />
    <%= f.text_field :myspace %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing band</h1>

<%= render 'form' %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<h1>Listing bands</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Website</th>
    <th>Facebook</th>
    <th>Myspace</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bands.each do |band| %>
  <tr>
    <td><%= band.name %></td>
    <td><%= band.description %></td>
    <td><%= band.website %></td>
    <td><%= band.facebook %></td>
    <td><%= band.myspace %></td>
    <td><%= band.location %></td>
    <td><%= link_to 'Show', band %></td>
    <td><%= link_to 'Edit', edit_band_path(band) %></td>
    <td><%= link_to 'Destroy', band, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Band', new_band_path %>

app/views/bands/new.html.erb
<h1>New band</h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @band.name %>
</p>

<p>
  <b>Description:</b>
  <%= @band.description %>
</p>

<p>
  <b>Website:</b>
  <%= @band.website %>
</p>

<p>
  <b>Facebook:</b>
  <%= @band.facebook %>
</p>

<p>
  <b>Myspace:</b>
  <%= @band.myspace %>
</p>

<p>
  <b>Location:</b>
  <%= @band.location %>
</p>


<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Battleofthebands</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'rails.js', 'jquery.min.js', 'jquery_ujs.js' %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song, :html => { :multipart => true }) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :lyrics %><br />
    <%= f.text_field :lyrics %>
  </div>
  <div class="field">
   <%= f.label :audio %><br />
  <%= f.file_field :audio %>
  </div>

<div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Lyrics</th>
    <th>Band</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.each do |song| %>
  <tr>
    <td><%= song.name %></td>
    <td><%= song.description %></td>
    <td><%= song.lyrics %></td>
    <td><%= song.band_id %></td>
    <td><%= link_to song.audio.url, song.audio.url %></td>
    <td><%= link_to 'Show', song %></td>
    <td><%= link_to 'Edit', edit_song_path(song) %></td>
    <td><%= link_to 'Delete', song, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @song.name %>
</p>

<p>
  <b>Description:</b>
  <%= @song.description %>
</p>

<p>
  <b>Lyrics:</b>
  <%= @song.lyrics %>
</p>

<p>
  <b>Band:</b>
  <%= @song.band_id %>
</p>


<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>